### ISSUE TITLE
How to view in the quest?

### ISSUE THREAD

**Issue by Bailey-24** [UT-Austin-RobIn/telemoma#4]
Hello, thank for your great work.
I can control the robot in simulation using VR, and view in the my computer.
But it can't view in the VR.
How to solve? (I don't need to control the real robot, I just want to control the simulation robot. )
![image](https://github.com/user-attachments/assets/8518b1a7-030b-4001-bd70-174b273d3a28)

I just can see the menu in the VR, not the robot view.

And It's very hard to use VR to control the robot, I can't control the robot to where i want to.

**Comment by Bailey-24** [comment]
![image](https://github.com/user-attachments/assets/f7b48dca-4201-4eb4-9dcd-f638eea3801f)


It't that only can view in real robot?

**Comment by ShivinDass** [comment]
Hi @Bailey-24, the VR headset is only used for tracking and we don't render the view on the VR screen. As shown by the image you posted, the VR can be worn over the head without covering the eyes to ensure that you can see the robot or computer screen while teleoperating a real or sim robot respectively. 

Regarding your question about difficulty to control the robot in simulation -- it'd be helpful to get some more info on what kinds of difficulty you're facing so I can help better. From my experience there can be two main reasons,
1. Action gains are not properly set -> You can try playing around with the scaler values in front of the actions [here](https://github.com/UT-Austin-RobIn/telemoma/blob/35d30162d88b70986a787c81618226c1d9f2017a/telemoma/robot_interface/igibson/fetch.py#L57) and setting them to something that you're comfortable with.
2. The VR coordinate frame is incorrectly initialized -> This can easily be reset when you start the teleop script by following the Note 1 provided [here](https://github.com/UT-Austin-RobIn/telemoma/tree/main/telemoma/human_interface#oculus).

**Comment by Bailey-24** [comment]
Thanks. I can control fetch more comfortable with VR.

But I have two more questions.
I can't control well using Realsense, even though I have follow the human interfere.
I want to know there is any tips, like Keep my hands straight or Bend the handle to a certain angle in the initial state.

The other question is I can't control the franaka panada's gripper in Omnigison environment, but I can control the other robots gripper.
Where can I find the solution.

Thank you.

**Comment by ShivinDass** [comment]
Hi @Bailey-24, the Realsense could be a little noisy but you should be able to use it for controlling some basic behaviors. You can refer to [this](https://robin-lab.cs.utexas.edu/telemoma-web/static/videos/teleoperation/dusting.mp4) video on your website for some insights. Generally,
1. Try to have a neutral background
2. Keep your palms facing the camera when the reference is being set
3. The mediapipe hand tracker is very noisy when hands are flat with respect to the camera, so try to use other modalities (such as VR) for tasks that require such behaviors.

Regarding the franka panda's gripper in omnigibson, what teleop interface are you using to control the arm? Is the behavior consistent with other teleop interfaces? Maybe @wensi-ai can provide more information regarding this.

**Comment by ShivinDass** [comment]
Since the original question about meta quest is resolved I am closing this issue. @Bailey-24 feel free to open another one with your above questions if they still persist.

**Comment by wensi-ai** [comment]
Hi @Bailey-24 apologies for the late reply, looks like there is bug in the OmniGibson codebase. You can change the last two zeros to 1.0 [in this line](https://github.com/StanfordVL/OmniGibson/blob/main/omnigibson/robots/franka.py#L96) in the OmniGibson codebase. We will fix this in our next release. Thanks for pointing this out!
